---
title: Caitlin Ward
author: ''
---

### Methodological Publications

<p>
<ol>
  <li> **Ward, C.**, Brown, G., Oleson, J. (2021). An Individual Level Infectious Disease Model in the Presence of Uncertainty from Multiple, Imperfect Diagnostic Tests. *Biometrics*. 
  doi: <a href="https://doi.org/10.1111/biom.13579">10.1111/biom.13579</a>  </li>
  <li> **Ward, C.**, Oleson, J., Tomblin, B., Walker, E. (2020). Modeling Population and Subject-Specific Growth in a Latent Trait Measured by Multiple Instruments over Time using a Hierarchical Bayesian Framework. *Journal of Applied Statistics*.
  doi: <a href="https://www.tandfonline.com/doi/abs/10.1080/02664763.2020.1817346?journalCode=cjas20">10.1080/02664763.2020.1817346</a> </li>
  <li> **Ward, C.**, Oleson, J., Jones, K., Charlton, M. (2018). Showcasing Cancer Incidence and Mortality in Rural ZCTAs Using Risk Probabilities via Spatio-temporal Bayesian Disease Mapping. *Applied Spatial Analysis and Policy*. 
  doi: <a href="https://link.springer.com/article/10.1007/s12061-018-9276-4">10.1007/s12061-018-9276-4</a> </li>
</ol>

</p>


### Selected Collaborative Publications


<p>
<ol>
  <li> Lence, T., Lockwood, G. M., Storm D. W., **Ward, C.**, Cooper, C. S. (2021). The Utility of Renal Sonographic Measurements in Differentiating Children with High Grade Congenital Hydronephrosis. *Journal of Pediatric Urology*.
  doi: <a href="https://www.sciencedirect.com/science/article/pii/S1477513121003594?via%3Dihub">10.1016/j.jpurol.2021.07.021</a>  </li>
  <li> Bathla G., Priya, S., Lui, Y., \textbf{Ward, C.}, Le, N., Neetu, S., Maheshwarappa, R., Monga, V., Zhang, H., Sonka, M. (2021). Radiomics-based Differentiation Between Glioblastoma and Primary Central Nervous System Lymphoma: A Comparison of Diagnostic Performance Across Different MRI Sequences and Machine Learning Techniques. European Radiology. 
  doi: <a href="https://link.springer.com/article/10.1007%2Fs00330-021-07845-6">10.1007/s00330-021-07845-6</a>  </li>
  <li> Priya, S., Agarwal, A., **Ward, C.**, Locke, T., Monga, V., Bathla G. (2021) Survival prediction in glioblastoma on post-contrast magnetic resonance imaging using filtration based first-order texture analysis: Comparison of multiple machine learning models. *The Neuroradiology Journal*. 
  doi: <a href="https://journals.sagepub.com/doi/full/10.1177/1971400921990766">10.1177/1971400921990766</a>  </li>
  <li> Priya, S., Aggarwal, T., **Ward, C.**, Bathla, G., Jacob, M., Gerke, A., Hoffman, E., Nagpal, P. (2021). Radiomics side experiments and DAFIT approach in identifying pulmonary hypertension using Cardiac MRI derived radiomics based machine learning models. *Scientific Reports*. 
  doi: <a href="https://journals.sagepub.com/doi/10.1177/1971400921990766">10.1038/s41598-021-92155-</a>  </li>
  <li> Hartley, C. C., Renner, L. M., \& **Ward, C.** (2019). A New Factor Solution for the Domestic Violence–Related Financial Issues Scale (DV-FI). *Journal of Interpersonal Violence*.
  doi: <a href="https://journals.sagepub.com/doi/10.1177/0886260519860888">10.1177/0886260519860888</a>  </li>
  <li> Saletta, M., Goffman, L., **Ward, C.**, \& Oleson, J. (2018). Influence of Language Load on Speech Motor Skill in Children With Specific Language Impairment. *J Speech Lang Hear Res*
  doi: <a href="https://pubs.asha.org/doi/10.1044/2017_JSLHR-L-17-0066">10.1044/2017\_JSLHR-L-17-0066</a>  </li>
</ol>

</p>

